In [2]:
import pandas as pd
import numpy as np

In [3]:
matches=pd.read_csv("IPL_Matches_2008_2022.csv")
ball=pd.read_csv("IPL_Ball_by_Ball_2008_2022.csv")

In [4]:
matches_detail=matches.merge(ball,on="ID")

In [5]:
matches_detail["Team1"]=matches_detail["Team1"].str.replace("Deccan Chargers","Sunrisers Hyderabad")
matches_detail["Team2"]=matches_detail["Team2"].str.replace("Deccan Chargers","Sunrisers Hyderabad")
matches_detail["Team1"]=matches_detail["Team1"].str.replace("Delhi Daredevils","Delhi Capital")
matches_detail["Team2"]=matches_detail["Team2"].str.replace("Delhi Daredevils","Delhi Capital")
matches_detail["Team1"]=matches_detail["Team1"].str.replace("Kings XI Punjab","Punjab Kings")
matches_detail["Team2"]=matches_detail["Team2"].str.replace("Kings XI Punjab","Punjab Kings")
matches_detail["City"]=matches_detail["City"].str.replace("Bangalore","Bengaluru")

In [6]:
matches_detail.iloc[1]

ID                                                             1312200
City                                                         Ahmedabad
Date                                                        2022-05-29
Season                                                            2022
MatchNumber                                                      Final
Team1                                                 Rajasthan Royals
Team2                                                   Gujarat Titans
Venue                                 Narendra Modi Stadium, Ahmedabad
TossWinner                                            Rajasthan Royals
TossDecision                                                       bat
SuperOver                                                            N
WinningTeam                                             Gujarat Titans
WonBy                                                          Wickets
Margin                                                             7.0
method                                                             NaN
Player_of_Match                                              HH Pandya
Team1Players         ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
Team2Players         ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...
Umpire1                                                    CB Gaffaney
Umpire2                                                    Nitin Menon
innings                                                              1
overs                                                                0
ballnumber                                                           2
batter                                                     YBK Jaiswal
bowler                                                  Mohammed Shami
non-striker                                                 JC Buttler
extra_type                                                     legbyes
batsman_run                                                          0
extras_run                                                           1
total_run                                                            1
non_boundary                                                         0
isWicketDelivery                                                     0
player_out                                                         NaN
kind                                                               NaN
fielders_involved                                                  NaN
BattingTeam                                           Rajasthan Royals
Name: 1, dtype: object

In [7]:
matches_detail

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Bengaluru,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225950,335982,Bengaluru,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225951,335982,Bengaluru,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225952,335982,Bengaluru,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225953,335982,Bengaluru,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,...,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore

In [8]:
team=["Chennai Super Kings","Delhi Capitals","Gujarat Titans","Punjab Kings","Lucknow Super Giants","Mumbai Indians","Kolkata Knight Riders","Rajasthan Royals","Royal Challengers Bangalore","Sunrisers Hyderabad"]

In [9]:
matches_detail=matches_detail[(matches_detail["Team1"].isin(team)) & (matches_detail["Team2"].isin(team) )]

In [10]:
total_score=matches_detail.groupby(["ID","innings"])["total_run"].sum()
total_score=total_score.reset_index()
ts=total_score[total_score["innings"]==1]

In [11]:
matches_detail=matches_detail[matches_detail["innings"]==2]

In [12]:
matches_detail=matches_detail.merge(ts,on="ID")

In [13]:
matches_detail["runs"]=matches_detail.groupby("ID")["total_run_x"].cumsum()

In [14]:
matches_detail["runs_left"]=matches_detail["total_run_y"]-matches_detail["runs"]

In [15]:
matches_detail=matches_detail[matches_detail["runs_left"]>=0]

In [16]:
def result(row):
    return 1 if row["BattingTeam"]==row["WinningTeam"] else 0

In [17]:
matches_detail["result"]=matches_detail.apply(result,axis=1)

In [18]:
matches_detail.sample()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,innings_y,total_run_y,runs,runs_left,result
23065,1181764,Chennai,2019-05-07,2019,Qualifier,Chennai Super Kings,Mumbai Indians,MA Chidambaram Stadium,Chennai Super Kings,bat,...,0,NaN,NaN,NaN,Mumbai Indians,1,131,22,109,1

In [19]:
matches_detail["wickets_left"]=10-matches_detail.groupby("ID")["isWicketDelivery"].cumsum()

In [20]:
matches_detail[matches_detail["innings_x"]==1]

Empty DataFrame
Columns: [ID, City, Date, Season, MatchNumber, Team1, Team2, Venue, TossWinner, TossDecision, SuperOver, WinningTeam, WonBy, Margin, method, Player_of_Match, Team1Players, Team2Players, Umpire1, Umpire2, innings_x, overs, ballnumber, batter, bowler, non-striker, extra_type, batsman_run, extras_run, total_run_x, non_boundary, isWicketDelivery, player_out, kind, fielders_involved, BattingTeam, innings_y, total_run_y, runs, runs_left, result, wickets_left]
Index: []

[0 rows x 42 columns]

In [21]:
ball

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225950,335982,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225951,335982,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225952,335982,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225953,335982,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore

In [22]:
matches_detail["balls_left"]=120-(matches_detail["overs"]*6+matches_detail["ballnumber"])

In [23]:
matches_detail=matches_detail[matches_detail["balls_left"]!=0]

In [24]:
matches_detail["CRR"]=matches_detail["runs"]*6/(120-matches_detail["balls_left"])

In [25]:
matches_detail["RRR"]=matches_detail["runs_left"]*6/(matches_detail["balls_left"])

In [26]:
def bowl(row):
    if row["BattingTeam"]!=row["Team1"]:
        return row["Team1"]
    else:
        return row["Team2"]

In [27]:
matches_detail["BowlingTeam"]=matches_detail.apply(bowl,axis=1)

In [28]:
matches_detail.iloc[170]

ID                                                             1312199
City                                                         Ahmedabad
Date                                                        2022-05-27
Season                                                            2022
MatchNumber                                                Qualifier 2
Team1                                      Royal Challengers Bangalore
Team2                                                 Rajasthan Royals
Venue                                 Narendra Modi Stadium, Ahmedabad
TossWinner                                            Rajasthan Royals
TossDecision                                                     field
SuperOver                                                            N
WinningTeam                                           Rajasthan Royals
WonBy                                                          Wickets
Margin                                                             7.0
method                                                             NaN
Player_of_Match                                             JC Buttler
Team1Players         ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
Team2Players         ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
Umpire1                                                    CB Gaffaney
Umpire2                                                    Nitin Menon
innings_x                                                            2
overs                                                                9
ballnumber                                                           5
batter                                                      JC Buttler
bowler                                                    PWH de Silva
non-striker                                                  SV Samson
extra_type                                                         NaN
batsman_run                                                          1
extras_run                                                           0
total_run_x                                                          1
non_boundary                                                         0
isWicketDelivery                                                     0
player_out                                                         NaN
kind                                                               NaN
fielders_involved                                                  NaN
BattingTeam                                           Rajasthan Royals
innings_y                                                            1
total_run_y                                                        157
runs                                                               103
runs_left                                                           54
result                                                               1
wickets_left                                                         9
balls_left                                                          61
CRR                                                          10.474576
RRR                                                           5.311475
BowlingTeam                                Royal Challengers Bangalore
Name: 171, dtype: object

In [29]:
final=matches_detail[["BattingTeam","BowlingTeam","City","runs_left","total_run_y","balls_left","wickets_left","CRR","RRR","result"]]

In [30]:
final

,BattingTeam,BowlingTeam,City,runs_left,total_run_y,balls_left,wickets_left,CRR,RRR,result
0,Gujarat Titans,Rajasthan Royals,Ahmedabad,130,130,119,10,0.000000,6.554622,1
1,Gujarat Titans,Rajasthan Royals,Ahmedabad,130,130,118,10,0.000000,6.610169,1
2,Gujarat Titans,Rajasthan Royals,Ahmedabad,129,130,117,10,2.000000,6.615385,1
3,Gujarat Titans,Rajasthan Royals,Ahmedabad,129,130,116,10,1.500000,6.672414,1
4,Gujarat Titans,Rajasthan Royals,Ahmedabad,129,130,115,10,1.200000,6.730435,1
...,...,...,...,...,...,...,...,...,...,...
79828,Royal Challengers Bangalore,Kolkata Knight Riders,Bengaluru,142,222,31,1,5.393258,27.483871,0
79829,Royal Challengers Bangalore,Kolkata Knight Riders,Bengaluru,141,222,30,1,5.400000,28.200000,0
79830,Royal Challengers Bangalore,Kolkata Knight Riders,Bengaluru,141,222,29,1,5.340659,29.172414,0
79831,Royal Challengers Bangalore,Kolkata Knight Riders,Bengaluru,140,222,29,1,5.406593,28.965517,0
79832,Royal Challengers Bangalore,Kolkata Knight Riders,Bengaluru,140,222,28,0,5.347826,30.000000,0

In [31]:
x=final.iloc[:,:-1]
y=final.iloc[:,-1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
trf=ColumnTransformer([
    ("trf",OneHotEncoder(sparse_output=False,drop="first"),["BattingTeam","BowlingTeam","City"])
],remainder="passthrough")

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

In [34]:
pipe=Pipeline(steps=[
    ("step1",trf),
    ("step2",LogisticRegression(solver="liblinear"))
])

In [35]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['BattingTeam', 'BowlingTeam',
                                                   'City'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [36]:
y_pred=pipe.predict(x_test)

In [37]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8061482136093927

In [38]:
pipe.predict_proba(x_test)[170]

array([0.63216287, 0.36783713])

In [39]:
import pickle

In [40]:
pickle.dump(pipe,open("pipe.pkl","wb"))

In [41]:
matches_detail["City"].unique()

<ArrowStringArray>
[     'Ahmedabad',        'Kolkata',         'Mumbai',    'Navi Mumbai',
           'Pune',          'Dubai',        'Sharjah',      'Abu Dhabi',
          'Delhi',        'Chennai',              nan,      'Hyderabad',
  'Visakhapatnam',     'Chandigarh',      'Bengaluru',         'Jaipur',
         'Indore',         'Ranchi',        'Cuttack',     'Dharamsala',
         'Nagpur',   'Johannesburg',      'Centurion',         'Durban',
 'Port Elizabeth',      'Kimberley',    'East London',      'Cape Town']
Length: 28, dtype: str

In [42]:
import sklearn
print(sklearn.__version__)

1.8.0

In [43]:
pip show scikit-learn

Name: scikit-learn
Version: 1.8.0
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author:
Author-email:
License-Expression: BSD-3-Clause
Location: c:\Users\sm\AppData\Local\Programs\Python\Python313\Lib\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by:
Note: you may need to restart the kernel to use updated packages.